name: Website CI/CD

on:
  push:
    branches:
      - main

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform
        run: terraform validate

      # Optional lint step (skip npm)
      - name: Run HTML/CSS/JS Lint (optional)
        run: |
          echo "Skipping npm steps for static site."
          # If needed, use htmlhint or stylelint via Docker

  deploy:
    needs: quality-gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Backup current S3 files
        run: |
          echo "Backing up current S3 files..."
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 sync s3://your-bucket-name s3://your-bucket-name-backup-$TIMESTAMP

      - name: Sync files to S3
        run: |
          aws s3 sync ./website s3://your-bucket-name --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"

  rollback:
    needs: deploy
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Rollback to backup
        run: |
          echo "Deploy failed. Rolling back to backup..."
          # Find the latest backup folder
          LATEST_BACKUP=$(aws s3 ls s3://your-bucket-name-backup/ | sort | tail -n 1 | awk '{print $2}')
          echo "Restoring backup: $LATEST_BACKUP"
          aws s3 sync s3://your-bucket-name-backup/$LATEST_BACKUP s3://your-bucket-name --delete
          # Invalidate CloudFront again after rollback
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"

